# Generated by Django 5.0.3 on 2024-03-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
    ]
